# Workflow to push to Amplify on commit
name: Amplify CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]
    paths: [ 'amplify/**' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency: AmplifyCD

jobs:
  amplify-deploy:
    runs-on: ubuntu-latest
    environment: AmplifyCD

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: configure amplify
        uses: ambientlight/amplify-cli-action@0.2.2
        with:
          amplify_command: configure
          amplify_env: alpha
          amplify_arguments: --categories {"auth":{"googleAppIdUserPool":"${{ secrets.AMPLIFY_GOOGLE_CLIENT_ID }}","googleAppSecretUserPool":"${{ secrets.AMPLIFY_GOOGLE_CLIENT_SECRET }}"}}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: install, build and test
        run: |
          npm install
          npm run build
          npm run test:unit

      - name: deploy
        uses: ambientlight/amplify-cli-action@0.2.2
        with:
          amplify_command: push
          amplify_env: alpha
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: integration test after push
        run: |
          npm run test:integ

      - name: Report Status
        uses: ravsamhq/notify-slack-action@v1
        if: always()
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}