# Workflow to regularly run tests
name: Backend Canary

# Controls when the action will run.
on:
  # Triggers the workflow every hour
  schedule:
    - cron: '0 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-canary:
    runs-on: ubuntu-latest
    environment: AmplifyCD

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: configure amplify
        uses: ambientlight/amplify-cli-action@0.2.2
        with:
          amplify_command: configure
          amplify_env: alpha
          amplify_arguments: --categories {"auth":{"googleAppIdUserPool":"${{ secrets.AMPLIFY_GOOGLE_CLIENT_ID }}","googleAppSecretUserPool":"${{ secrets.AMPLIFY_GOOGLE_CLIENT_SECRET }}"}}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: install, build and test (both unit and integ)
        run: |
          npm install
          npm run build
          npm run test